# Generated by Django 3.1.2 on 2021-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
