# Generated by Django 3.1.2 on 2020-12-23 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201221_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date follow'),
            preserve_default=False,
        ),
    ]
