# Generated by Django 3.1.2 on 2021-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210127_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
