# Generated by Django 3.1.2 on 2020-12-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_follow_following_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='title',
        ),
    ]
