# Generated by Django 3.1.2 on 2020-12-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201224_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
